language: generic
os: osx
matrix:
  include:
    - os: linux
      sudo: required
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - os: linux
      sudo: required
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
compiler:
  - clang
  - gcc
script:
  - mkdir build && cd build
  - cmake -DUSE_CPM:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF .. 
  - make
  - make install
  - cd .. && rm -rf build && mkdir build && cd build
  - cmake -DUSE_CPM:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_TESTS_FOR_Webdavclient:BOOL=ON ..
  - make
