language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
  - mkdir build && cd build
  - cmake -DUSE_CPM:BOOL=ON .. 
  - make
  - make install
  - cd .. && rm -rf build && mkdir build && cd build
  - cmake -DUSE_CPM:BOOL=ON -DBUILD_TESTS_FOR_Webdavclient:BOOL=ON ..
  - make
